Repository PankajSingh2003/NASA_startingpage, pull requests merged in 2022-10, with the labels that each got.

#13 Update index.html
  index.html
Labels: good first issue, hacoberfest

#22 Update index.html
  index.html
Labels: good first issue, hacktoberfest

#34 Update index.html
  index.html
Labels: hacktoberfest
